In [2]:
import numpy as np


In [5]:
person_height = [5.2,5,4,5.2,6.2,7.4,8,6.7]
person_weight = [88, 86,55,66,42,54,56,89]
person_height = np.array(person_height)
person_weight = np.array(person_weight)
person_height,person_weight


(array([5.2, 5. , 4. , 5.2, 6.2, 7.4, 8. , 6.7]),
 array([88, 86, 55, 66, 42, 54, 56, 89]))

In [9]:
print(person_height[0:3:5])

[5.2]


In [12]:
example = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
example

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(example[0,2])


3


In [37]:
example1 = np.array([10,11,12,13,14])
example2 = np.arange(5)
example3 = example1 + example2
example4 = example3 >= 17
example4
example5 = np.array([1,2,4,5,6,7,8])
example5.sum()



1

In [39]:
example5.min()

1

In [40]:
np.power(example5,2)



array([ 1,  4, 16, 25, 36, 49, 64], dtype=int32)

In [6]:
array_x = np.array([11,22,13])
array_y= np.array([23,22,22])
np.concatenate([array_x,array_y])
array_z= np.concatenate([array_x,array_y])

In [7]:
np.split([arange()])

TypeError: _split_dispatcher() missing 1 required positional argument: 'indices_or_sections'